# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_win_Vote_Menu(object):
    def setupUi(self, win_Vote_Menu):
        win_Vote_Menu.setObjectName("win_Vote_Menu")
        win_Vote_Menu.resize(500, 500)
        win_Vote_Menu.setMinimumSize(QtCore.QSize(500, 500))
        win_Vote_Menu.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(parent=win_Vote_Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Vote_Menu = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Vote_Menu.setGeometry(QtCore.QRect(210, 50, 61, 16))
        self.lbl_Vote_Menu.setObjectName("lbl_Vote_Menu")
        self.lbl_Candidate_Menu = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Candidate_Menu.setGeometry(QtCore.QRect(200, 50, 91, 16))
        self.lbl_Candidate_Menu.setObjectName("lbl_Candidate_Menu")
        self.btn_Vote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Vote.setGeometry(QtCore.QRect(130, 120, 75, 23))
        self.btn_Vote.setObjectName("btn_Vote")
        self.btn_Back_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Back_1.setGeometry(QtCore.QRect(130, 120, 75, 23))
        self.btn_Back_1.setObjectName("btn_Back_1")
        self.btn_Results = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Results.setGeometry(QtCore.QRect(240, 120, 75, 23))
        self.btn_Results.setObjectName("btn_Results")
        self.btn_Close = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Close.setGeometry(QtCore.QRect(240, 120, 75, 23))
        self.btn_Close.setObjectName("btn_Close")
        self.lbl_Bianca_Total = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Bianca_Total.setGeometry(QtCore.QRect(120, 230, 81, 16))
        self.lbl_Bianca_Total.setObjectName("lbl_Bianca_Total")
        self.lbl_Edward_Total = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Edward_Total.setGeometry(QtCore.QRect(120, 250, 81, 16))
        self.lbl_Edward_Total.setObjectName("lbl_Edward_Total")
        self.lbl_Felicia_Total = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Felicia_Total.setGeometry(QtCore.QRect(120, 270, 81, 16))
        self.lbl_Felicia_Total.setObjectName("lbl_Felicia_Total")
        self.lbl_Total = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Total.setGeometry(QtCore.QRect(120, 290, 81, 16))
        self.lbl_Total.setObjectName("lbl_Total")
        self.btn_Bianca = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Bianca.setGeometry(QtCore.QRect(80, 160, 75, 23))
        self.btn_Bianca.setObjectName("btn_Bianca")
        self.btn_Edward = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Edward.setGeometry(QtCore.QRect(180, 160, 75, 23))
        self.btn_Edward.setObjectName("btn_Edward")
        self.btn_Felicia = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Felicia.setGeometry(QtCore.QRect(280, 160, 75, 23))
        self.btn_Felicia.setObjectName("btn_Felicia")
        self.btn_Back_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Back_2.setGeometry(QtCore.QRect(180, 350, 75, 23))
        self.btn_Back_2.setObjectName("btn_Back_2")
        self.lbl_Voted_For = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Voted_For.setGeometry(QtCore.QRect(200, 200, 111, 16))
        self.lbl_Voted_For.setObjectName("lbl_Voted_For")
        win_Vote_Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=win_Vote_Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        win_Vote_Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=win_Vote_Menu)
        self.statusbar.setObjectName("statusbar")
        win_Vote_Menu.setStatusBar(self.statusbar)

        self.retranslateUi(win_Vote_Menu)
        QtCore.QMetaObject.connectSlotsByName(win_Vote_Menu)

    def retranslateUi(self, win_Vote_Menu):
        _translate = QtCore.QCoreApplication.translate
        win_Vote_Menu.setWindowTitle(_translate("win_Vote_Menu", "Voting Menu"))
        self.lbl_Vote_Menu.setText(_translate("win_Vote_Menu", "Vote Menu"))
        self.lbl_Candidate_Menu.setText(_translate("win_Vote_Menu", "Candidate Menu"))
        self.btn_Vote.setText(_translate("win_Vote_Menu", "Vote"))
        self.btn_Back_1.setText(_translate("win_Vote_Menu", "Back"))
        self.btn_Results.setText(_translate("win_Vote_Menu", "Results"))
        self.btn_Close.setText(_translate("win_Vote_Menu", "Close"))
        self.lbl_Bianca_Total.setText(_translate("win_Vote_Menu", "Bianca - 0"))
        self.lbl_Edward_Total.setText(_translate("win_Vote_Menu", "Edward - 0"))
        self.lbl_Felicia_Total.setText(_translate("win_Vote_Menu", "Felicia - 0"))
        self.lbl_Total.setText(_translate("win_Vote_Menu", "Total - 0"))
        self.btn_Bianca.setText(_translate("win_Vote_Menu", "Bianca"))
        self.btn_Edward.setText(_translate("win_Vote_Menu", "Edward"))
        self.btn_Felicia.setText(_translate("win_Vote_Menu", "Felicia"))
        self.btn_Back_2.setText(_translate("win_Vote_Menu", "Back"))
        self.lbl_Voted_For.setText(_translate("win_Vote_Menu", "Voted ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_Vote_Menu = QtWidgets.QMainWindow()
    ui = Ui_win_Vote_Menu()
    ui.setupUi(win_Vote_Menu)
    win_Vote_Menu.show()
    sys.exit(app.exec())
